=== Activity 1e: Expand national participation

==== Tasks
[lowerroman]
. Ensure GBIF.org interface and key content supported in relevant languages
. Improve coordination and mechanisms for engaging new countries
. Provide Governing Board with annual review and progress assessment for GBIF status and engagement in all countries

==== 2019 Progress

The internationalization of the GBIF.org user interface and core content elements, in the six UN languages as well as selected additional languages, is expected to be complete by the end of 2019.

Technical adjustments have been made to GBIF.org to accommodate right-to-left script needed for Arabic and other languages. A volunteer Arabic-speaking network is being developed. Translations of GBIF.org into Russian and Chinese (both simplified and traditional) are far progressed and are being launched later in 2019, adding to the existing interfaces and core content in English, French, Spanish, Portuguese and Japanese. 

Three 2019 regional meetings within the BID program are providing opportunities to strengthen and expand national participation in the Caribbean, Pacific and sub-Saharan Africa. The Caribbean meeting in Trinidad and Tobago was attended by over 40 participants from across the Latin American and Caribbean region, including a strong delegation from the host country coming from various institution and decision-making bodies. Strong attendance is expected in the other regional meetings later in 2019. 

The main outputs of the meetings are regional statements on regional priorities (e.g. from the Caribbean), and roadmaps for ensuring long term sustainability of biodiversity data sharing. The final day of the event focuses on node management training including the benefits of GBIF participation and being part of the GBIF nodes community. 

During 2019, Angola and Belarus joined the community as Associate Participants, and Chile returned to Voting Participant status after a period as an Associate Participant. Brazil communicated its intention to become a Voting Participant. Israel, Indonesia and India dropped to observer status after passing the maximum period as Associate Participants. Argentina, Ghana, Kenya, Uganda and the United Kingdom moved from Voting to Associate status on 1 January 2019 due to non-payment of their contributions for two consecutive years. A complete and updated progress assessment of the GBIF status and engagement in all countries is being presented at the GB26 meeting in the Netherlands.

===== 2019 Participant contributions

* *Tecala*: Did something really important.

==== 2020 Work items

*	The GBIF Secretariat will continue to identify funding opportunities for regional engagement, including inviting observers to regional node meetings. If budget allows, it will create a specific funding priority area alongside the 2020 CESP call for GBIF regional outreach activities, as outlined in regional participation strategies developed across the network.
*	The Secretariat will develop and implement engagement, data-mobilization and capacity-enhancement plans for greater participation in all global regions, with an emphasis on the underrepresented areas. This effort will be aided by capacity enhancement workshops, including through a second phase of BID and other supplementary funding that becomes available.
*	The internationalization of GBIF.org user interface, content and guidance materials will continue. Assuming the 2019 commitment for six UN languages is complete, this work will focus on maintenance and updates and will allow the addition of more languages on demand, and translating a wider set of content and materials, funded through both specific projects and volunteer efforts.
* Engagement, data mobilization and capacity enhancement campaign for Arabic-speaking region (€20,000, if funds allow).

===== 2020 Participant plans

* *Tecala*: Do something big.

==== Rationale

GBIF’s national membership has remained largely static in recent years. Active participation in the network is confined to a limited number of regions, with the most dynamic activity in node collaboration and data publication focused in Western Europe, North America, Latin America, Oceania, increasingly sub-Saharan Africa and limited parts of Asia. Thus, significant parts of the world have little or no direct involvement in GBIF’s activities, which poses a risk to the long-term credibility of GBIF as a global collaborative network. Secretariat staff and existing Participants constantly engage potential new members through ad hoc contacts, but the situation calls for a more strategic approach to expand membership.

==== Approach

The Secretariat will compile and maintain an up-to-date register of the status of GBIF engagement and relevant contacts in all countries, providing the Governing Board with an annual review that analyses progress and remaining gaps in membership across each region. Following the development of a coordinated engagement plan for each region, Participants and regional groups with strong contacts to relevant agencies in other governments may take the lead in engagement. The Secretariat will continue to develop strategic engagement through the CBD and other intergovernmental networks, as well as through the BID programme and other capacity-related activities. Adapting the GBIF.org interface to support key content in multiple languages will seek to address language barriers to national expansion, with targeted translation carried out both through external contracts and in-kind services provided by Participants.
