=== Activity 1f: Plan implementation

==== Tasks
[lowerroman]
. Develop better integration between nodes activities and Governing Board processes
. Expand regional meetings to serve as GBIF community Implementation Planning conferences and opportunities to develop fundable programmes of work
. Increase alignment between GBIF work programmes and activities of each GBIF Organisational Participant and Affiliate
. Explore increased alignment and joint organisation of workshops with other networks such as TDWG, SPNHC, GEO BON, RDA, etc.

==== 2019 Progress

GBIF leads work package five of the European initiative SYNTHESYS+ project, which includes running three workshops. The focus of these workshops, defined by the global community, is to be specified in Q3 2019, but is anticipated to include activities around collection cataloguing, richer specimen models and tracking of citations of specimens, collections and the individuals, all of which are also priorities for GBIFS (see also activity 1a).

The Secretariat has been involved at many organization levels (Steering Committee, Programming committee) of the Biodiversity_Next conference held in conjunction with GB26. Secretariat staff are involved in over 20 talks and organizing several sessions that relate directly to the Work Programme. Involvement has begun with a similar meeting scheduled to take place in September 2020 in Virginia, USA.

The Secretariat is developing standardized annual information requests based on the GBIF Strategic Plan and Implementation Plan structure aimed at capturing relevant updates and work plans from Participant nodes. The work is intended to improve the visibility of the GBIF Participants, and especially of the nodes, on GBIF.org and to better reflect the network as a whole, particularly with regard to the active contributions toward work programme implementation. 

The _alliance for biodiversity knowledge_ was established as an outcome of the 2018 GBIC2 conference hosted by GBIF in Copenhagen. The Secretariat has reconstituted the GBIC2 steering committee as the steering committee for the alliance. In conjunction with external stakeholders, the Secretariat is developing a virtual workshop infrastructure and will be hosting the first of a series of virtual workshops under this infrastructure later in 2019. The Secretariat is also driving efforts to develop and disseminate alliance communication materials and to build expertise networks for managing virtual workshops and networking models.

===== 2019 Participant contributions

* *Tecala*: Did something really important.

==== 2020 Work items

*	Convene SYNTHESYS+ workshops and integrate outcomes with relevant Work Programme activities.
*	Continue implementation and refinement of the standardized annual information requests from Participant nodes and display up to date content on revised country pages of GBIF.org.
*	Lead some and participate in all alliance for biodiversity knowledge virtual workshops that will be defined in key areas to increased alignment of GBIF with other networks and infrastructures. 
*	Manage and improve the virtual conferences infrastructure used by the alliance for biodiversity knowledge. Work with steering committee on a governance structure and prioritizing the alliance efforts. Expand communication effort through conferences and the ambassador network (minimum €10,000). Provide technical, communication and administrative support for the alliance.

===== 2020 Participant contributions

* *Tecala*: Do something really important.

==== Rationale

Implementing this plan hinges on effective coordination with the plans of individual GBIF national and organizational Participants. GBIF must also ensure that node activities are well recognized and integrated with other biodiversity research and informatics initiatives at national, regional and organizational levels.

==== Approach

To make national-scale implementation more central across the GBIF network, the Secretariat will consult with the Governing Board on models for unifying aspects of the work of the Nodes Committee into Governing Board meetings. The Secretariat also seeks funds to increase the scope of nodes meetings to include work to develop proposals for fundable activities aligned with this Implementation Plan, particularly by addressing regional priorities. The GBIF Secretariat will also engage organizational Participants to develop specific memoranda of cooperation in key areas and to identify and support alignments with this Implementation Plan and opportunities for joint organization of meetings and workshops.
