== Priority 1: Empower Global Network

****
Ensure that governments, researchers and users are equipped and supported to share, improve and use data through the GBIF network, regardless of geography, language or institutional affiliation.
****

=== Activity 1a: Focus on people

==== Tasks
[lowerroman]
. Develop mechanisms to support and reflect the skills, expertise and experience of individual and organizational contributions to the GBIF network (including revision of identity management system and integration of ORCID identifiers)
. Consolidate use of digital badges to record skills and contributions

==== 2019 Progress

The Secretariat informatics team has begun investigating citation tracking of individual records, and developing the ability for users to ‘claim’ data they have contributed, to promote use and to demonstrate the value proposition of GBIF. User profile work is scheduled to begin in late 2019 and early discussions have been initiated with GBIF Canada around lessons learned in claiming specimens through https://bloodhound-tracker.net[Bloodhound Tracker] and how to integrate that tool into GBIF.

The Secretariat has been carrying out an evaluation of the https://discourse.gbif.org[GBIF Community Forum] during its first year of operation, to inform a decision on whether to continue maintaining the platform. Preliminary metrics suggest that use of the forum by the community is well below the targets set as benchmarks when the platform was established as a successor to the GBIF Community Site. 336 posts were made over a year with 87 new topics started by non-Secretariat staff. On the other hand, the time spent by Secretariat staff on moderation/curation was not significant.

===== 2019 Participant contributions

* *Tecala*: Did something really important.

==== 2020 Work items

* Explore possibilities of providing citation tracking from dataset level to individual level. Provide ability to claim one’s data and promote use; explore building on the example of ‘Bloodhound tracker’ and moving it into core GBIF operations.
* Clearly communicate and demonstrate the benefits of ORCID use through citation tracking.
* Pending a decision on continuing the GBIF Community Forum, take steps to improve interactive engagement with the broader GBIF community, considering the views gathered during the 2019 survey.

===== 2020 Participant plans

* *Tecala*: Do something really important.

==== Rationale

GBIF is the result of work by thousands of people in agencies and institutions worldwide. This network’s long-term sustainability depends on demonstrating the value of such contributions and justifying continued investment of effort.

The GBIF Secretariat can enhance efforts to develop capacity within the network and build an effective distributed help desk system that acknowledges and showcases relevant skills and experience that people across the network possess. Users of GBIF data products would also benefit from showcasing the network’s indispensible human resources and their impact on assessing and improving biodiversity data.

For these reasons, the next round of improvements to GBIF.org should enhance the network’s capacity to serve as a hub for the GBIF community by identifying its active contributors, integrating information on their relevant GBIF activities, and supporting broader knowledge exchange and skill development.

==== Approach

The key task is to enhance GBIF.org to connect and display information on its contributors and other users of the site. This may include contact details (subject to individual control), formal roles (e.g. within participant delegations; in connection to publishing/improving datasets; based on training experience) and online participation in help desk discussions. Whether through the use of existing social or commercial platforms or through custom web application development, GBIF.org should absorb activity currently handled through the separate GBIF community site. GBIF should also build on experience during 2015-2016 in using digital badges to identify skills held by individuals. Such community functions will support the operation of GBIF Task Groups, externally funded projects like BID, and engagement of expert groups to curate GBIF data.
