=== Priority 3: Fill Data Gaps

****
Prioritize and promote mobilization of new data resources which combine with existing resources to maximize the coverage, completeness and resolution of GBIF data, particularly with respect to taxonomy, geography and time.
****

=== Activity 3a: Identify priority gaps

==== Tasks
[lowerroman]
. Organize and integrate requirements identified by fitness-for-use groups
. Establish open mechanism for researchers and users to document specific data needs
. Develop assessments and visualisations of strengths and weaknesses of GBIF data in key dimensions (taxonomic, geographic, environmental, temporal)
. Maintain well-publicized GBIF priorities for data publishing, incorporating needs of IPBES and other networks
. Provide Governing Board with annual review and progress assessment for digitisation of major natural history collections
. Provide GBIF Participants with actionable priorities and targets for content mobilization

==== 2019 Progress

During 2019 the Secretariat is developing actionable guidance for nodes, publishers and funders on addressing priority gaps through mobilization targets and strategies based on spatial, temporal, taxonomic and thematic dimensions of biodiversity data. This guidance document will indicate best practices on how to prioritize mobilization to develop national priorities and how to integrate those priorities into a mobilization strategy. The guide content undergoes assessments that can be updated upon knowledge gained for the GBIF communities in activities such as the global node events.

The Secretariat performed https://data-blog.gbif.org[data analyses] building on the input from the 2016 Ebbe-Nielsen Challenge. It further examined possible approaches of ‘hunger-mapping’ to the prioritization of data gaps, as well as analysing the availability and coverage of regional and national checklists of taxa that could support this approach, and the possibility of making use of ES50 maps as a measure of species richness.

===== 2019 Participant contributions

* *Tecala*: Did something really important.

==== 2020 Work items

*	Continue work on items initiated in late 2019, with an emphasis on developing actionable guidance for data publishers and nodes, integration of user needs into prioritization for data mobilization, and data search analysis.
*	Continue to improve visualizations of GBIF-mediated data that identify gaps by engaging in interactive community consultations. This work is a candidate for curated discussion through the alliance for biodiversity knowledge prior to implementation on GBIF.org.  

===== 2020 Participant plans

* *Tecala*: Do something big.

==== Rationale

GBIF has a range of tools, including fitness-for-use groups, other community consultations, feedback channels, direct communication with authors of scientific studies, and societal demands, to identify and collect data needs. The Ebbe Nielsen Challenge for 2016 focuses specifically on tools and algorithms to identify significant gaps. These gaps may relate to different facets of the data, including geography, taxonomy, time periods, and coverage of particular ecosystems or land units. Addressing these gaps may require focus on gaining additional occurrence records, targeting data areas missing from published records, or getting additional metadata elements. By consolidating and prioritising demands for data content, in the context of already accessible data and knowledge of resources which are not yet available as open data, GBIF will be positioned to inform collection and data holders, funding institutions and political decision makers of the most worthwhile and cost-effective ways to extend the available knowledge base.

==== Approach

The GBIF Secretariat will harmonize and document data mobilization demands from different sources. Simple tools are required to support needs capture, including informative documentation and justification for such demands. Automated assessment and reporting of gaps will be included where this proves possible and valuable. This combined information can support transparent decision making and target setting for gap-filling efforts, allowing all interested actors to step in at appropriate levels. GBIF will coordinate with efforts through the Intergovernmental Platform on Biodiversity and Ecosystem Services (IPBES) to identify and address significant knowledge and data gaps, including outreach and funding strategies for gap-filling . A thorough, regularly updated overview of data coverage in gbif.org both makes it easier to identify gaps, and to monitor progress and efficiency of mobilization efforts over time. GBIF should offer (e.g. annually) a brief report of significant gaps which need to be addressed. Such a report may be valuable to Participants and funding bodies to stimulate and evaluate digitisation and mobilisation options.
