=== Activity 4c: Enable data curation

==== Tasks
[lowerroman]
. Develop network-wide approach to handling and processing annotations and feedback
. Enhance IPT to offer dataset-level peer review and commentary mechanisms and record-level annotations
. Develop mechanism and tools within GBIF.org for sharing cleaned and annotated datasets based on GBIF downloads (“reference datasets”)
. Develop GBIF data workbench tool (within GBIF.org and possibly also as standalone) for cleaning and filtering network data (e.g. in red list assessments)
. Develop strategy and support mechanisms for expert communities to curate sections of GBIF data

==== 2019 Progress

A pilot handle-based server was deployed demonstrating GBIF infrastructure is capable to participate in a handle network and issue record identifiers.

===== 2019 Participant contributions

* *Tecala*: Did something really important.

==== 2020 Work items

*	Continue to explore the use of the GBIF data index to support stable persistent resolvable identifiers for all specimens and occurrence records.
*	Explore bidirectional data linking and synchronization with data management systems and publishers to achieve faster and more accurate mutual updates on data improvements and annotations (minimum €10,000).

===== 2020 Participant plans

* *Tecala*: Do something big.

==== Rationale

In a global network, curation of the shared data pool is increasingly becoming a joint responsibility of aggregators, publishers, experts and data users. The goal is to integrate corrections, improvements, additional information and analysis results in a timely manner, with better visibility to all network participants and data users. Expanding the existing knowledge base requires improved communication channels and workflows for collaboration between all actors, tools to capture and rapidly display new or improved information, commentary and data, and not least tools, credit systems and support to engage expert activities.

==== Approach

The main task is to provide tools and mechanisms that make it easy for users and experts to contribute knowledge to the available pool of data. Building on existing data filtering and data improvement workflows in the community, GBIF tools and mechanisms are to support the identification of relevant data, their cleaning and preparation for specific purposes, and the sharing of the results of such processes with the wider community. Input collected through existing feedback mechanisms (Jira feedback on gbif.org, AnnoSys, ...) is to be raised to a visibility level that supports and drives the usefulness of the published data.
