=== Activity 3d: Rescue datasets

==== Tasks
[lowerroman]
. Develop tools for reporting potential data sources for integration into GBIF
. Develop support materials (including accreditation) for collaborative data preparation and mapping datasets in GBIF
. Develop site and support mechanisms for users to adopt and map datasets
. Review and update definitions of data publisher within GBIF to reflect collaborative data publishing
. Develop partnerships with data journals to support data papers for rescued datasets

==== 2019 Progress

Explored metadata-only dataset publication of the datasets proposed through https://www.gbif.org/suggest-dataset. Currently developing categorization of datasets to improve implementation of the ‘Suggest a dataset’ tool in GitHub. 

==== 2019 Participant contributions

* *Tecala*: Did something really important.

==== 2020 Work items

*	Continue to implement workflow for prioritizing and drawing upon potential data sources reported through the ‘dataset catcher’ tool, including involvement of nodes, mentors and crowdsourced solutions.
*	Roll out a workflow for ‘Suggest a dataset’ processing.

==== 2020 Participant plans

* *Tecala*: Do something big.

==== Rationale

Many researchers hold potentially valuable data which are not yet in a suitable digital format for integration into GBIF. Historical publications are a similar source of valuable data which remain inaccessible. This offers an opportunity to establish a community platform to capture information on such datasets where the researcher or owner lacks the time or capability to make the data available as a GBIF-compatible dataset, and to enable interested individuals to volunteer time to collaborate with the owner to publish a dataset, potentially in conjunction with a data paper credited to all parties. Such a model may address a key bottleneck in bringing valuable data online.

==== Approach

The GBIF Secretariat, or an interested Participant, should develop a test environment to explore this model. The model should support identification of basic information on datasets which may be rescued, including details of ownership, etc. Volunteers may be required to undergo some training or demonstrate some knowledge of GBIF data publishing and the taxa concerned prior to adopting a dataset for mobilisation. Mobilisation should be include consultation or partnership with the owner and should deliver quality metadata and a valid mapping of the original information. Opportunities should be explored for publication of resulting datasets as data papers as an incentive to all parties.
