== Priority 5: Deliver Relevant Data

=== Activity 5a: Engage academia

==== Tasks
[lowerroman]
. Promote biodiversity informatics curriculum, support training of the users
. Publicize GBIF as data tool via university libraries and faculties
. Develop online collaboration through GBIF.org helpdesk to assist and support data users
. Represent GBIF at the relevant science fora, esp. at the frontier directions such as ecology and molecular research

==== 2019 Progress

The BioDATA project is a training programme for higher-education students from Tajikistan, Belarus, Ukraine, and Armenia that offers an intensive course of study leading to their certification in biodiversity data management. Launched in 2018 and running through 2021, the Finnish-funded programme has already engaged 23 volunteer mentors and is training half of the programme’s planned 64 students on GBIF publishing and data skills by the end of 2019. Altay State University, supported by a GBIFS letter, received funding to integrate GBIF and data education in regular biology training for the BSc and MSc programme, with 70 students expected to take part each year.

===== 2019 Participant contributions

* *Tecala*: Did something really important.

==== 2020 Work items

*	Conduct survey on how GBIF informatics is incorporated into relevant graduate and undergraduate curricula to identify gaps and opportunities and key entry points. Use survey findings to prepare a campaign that could roll out relevant resources through GBIF nodes in 2021.
*	Engage with academic-based projects that use or could use better GBIF data in their pipelines and protocols. If funding allows, hold a workshop to stimulate use (€25,000).

===== 2020 Participant plans

* *Tecala*: Do something big.

==== Rationale

The most significant user community for GBIF is academic researchers. Even policy-related uses of GBIF often derive from the work of such individuals. It is accordingly important for GBIF to understand the needs of researchers and academic societies and to communicate clearly regarding the tools and services GBIF can deliver. Communication should include information and support materials for students and early-career researchers, on both publication and use of data, including citation, use tracking and data papers. University faculties and libraries may be important channels for this information. In addition, GBIF needs to engage more closely with taxonomic societies and other academic bodies which could be key collaborators in curating and improving data. Achieving such an outcome depends on understanding how GBIF can become a more central tool for their work, so that work on digital knowledge directly benefits those who contribute.

==== Approach

GBIF Participants may be well-positioned to lead in engaging with taxonomic societies and other interested research groups, including assuming responsibility to serve as ambassadors for GBIF within particular communities. Particular focus should be given to opportunities to explore models for such communities to assist GBIF with data curation. Few university programs include clear guidance and promotion for open data sharing. GBIF should make use of its own documentation materials and of curriculum materials from throughout the GBIF community to engage with biological science faculties and university libraries to share information on GBIF tools and resources and practices.
