[#_gbif_implementation_plan_2017_2021]
== GBIF Implementation Plan 2017–2021

The GBIF Strategic Plan 2017–2021 presents five broad overlapping priorities for the GBIF network. Each of these priorities sets a direction and guides activities for the coming period. This document here presents an Implementation Plan to enable the GBIF community as a whole to make significant progress in each priority area. It establishes the framework for GBIF’s Annual Work Programmes over the period of the Strategic Plan.

The following notes provide context for the activities outlined here.

=== Delivery

Some activities in this plan will be led or coordinated by GBIF Secretariat staff, using core or supplementary funds. Other activities may be led or coordinated by GBIF Participants with particular interest or expertise in the areas in question.

Combining energies across the whole network within the framework of this plan will enable GBIF to progress the set of activities identified in this document more rapidly. Each Annual Work Programme in the period 2017 to 2021 will build on progress in past years and will focus available resources on remaining priorities identified in this document.

=== Structure of GBIF

GBIF operates on three primary levels:

* *Global* – GBIF is an international activity and works at the global level to increase standardization and adoption of best practices, to facilitate sharing of expertise and resources and to offer an integrated global dataset and associated informatics infrastructure.
* *Participant* – GBIF Participants, including the nodes that they establish, have primary responsibility for engaging stakeholder communities, mobilizing and curating data, providing support and training, and ensuring that national researchers and agencies gain maximum benefit from GBIF. GBIF regional networks provide a framework for national and organizational stakeholders to collaborate more closely, particularly when addressing challenges and opportunities they share.
* *Data Publisher* – Data-holding institutions, agencies and individual researchers are the foundations on which GBIF depends. GBIF has a responsibility to ensure that data publishers have access to the tools and support that they need and that they receive recognition for their work and contributions.

This Implementation Plan seeks to address needs at all three of these levels while aiming to reinforce the value of GBIF for stakeholders at each level. It is highly desirable to increase coordination and feedback between these levels. The 2019 version of the document includes reports from a few GBIF Participants on their 2018 activities and 2019 plans. It would be most beneficial to receive inputs from a wider range of Participants to give a clear picture of everything occurring in the network and to assist the Secretariat and all Participants with better alignment and reuse.

A particular requirement is for the GBIF network to maintain and coordinate software to support each of these levels and to ensure that the publication, integration, management and use of data are as efficient as possible.

At the global level, GBIF focuses on delivery of GBIF.org as a software platform to support both human users and tools (via web services). Many of GBIF’s goals depend on being able to deliver a fully integrated view of all data from all sources in the best possible forms.

At the data publisher level, GBIF maintains the Integrated Publishing Toolkit (IPT) as its default tool for sharing GBIF-compatible data. Ongoing enhancements are required to increase both the usability of this tool and the value that its services provide to data publishers. At the same time, GBIF seeks to support GBIF-compatible data publishing via other tools such as collection management systems and citizen science platforms.

At the Participant level, several efforts have been made to deliver generic portal tools to assist node managers in their work and to deliver value at the national level. The most significant roles for such a platform would be to:

* Enable national- or regional-level integration and curation of datasets
* Enhance data records to reflect national administrative units and national species lists
* Provide tools that meet the requirements of national or regional researchers, policymakers and the general public

Over the last few years, a growing number of GBIF Participants have collaborated to leverage Australia’s investment in the Atlas of Living Australia (ALA) and to customize these tools to deliver their own portals. The Implementation Plan responds to this with a focus on increasing community development and support to deliver a reusable and sustainable portal toolkit based on the ALA tools. This approach not only benefits Participants already committed to using these tools, but also provides a solution for rapid adoption by other Participants at national, regional, or even thematic levels. In addition, Belgium has indicated an interest in exploring the potential for an alternative lightweight solution based on repository tools such as CKAN.

The vision for the technical aspects underlying this Implementation Plan is that the components developed and offered by the GBIF network at each scale should combine to deliver a robust solution to support GBIF data management and that together they should continue to evolve to support a leading international data infrastructure. One aspect of this will be to ensure that all users can share and reuse common components such as data validation tests and that GBIF promotes and fosters wider activity around open projects.

GBIF is more than just a technical network, and this Implementation Plan also addresses the capacity enhancement, networking, communication and reporting activities necessary to advance GBIF’s work in these areas. Since it is impossible for GBIF to support all aspects of its network using core funds, this plan focuses on resources which will support the work of GBIF Participants and data holders everywhere, coordinating the skills, expertise and investment of the whole network to maximize benefits to all stakeholders.

=== Timeline

None of the priorities, or the more specific goals identified for each priority, can be achieved in a single year; each will require coordinated effort across multiple annual work programmes. This document describes the set of activities currently recognized as important to deliver the Strategic Plan over the five-year period. It will be revised and expanded as required each year to address changes in the landscape in which GBIF operates.

This Implementation Plan was presented for approval by the Governing Board at GB23. It was accompanied by the Annual Work Programme for 2017. Both components were approved at the meeting.

Additional commitments from GBIF Participants or others to contribute or deliver particular elements will be welcomed throughout the five-year implementation period.

=== Resources

GBIF has a range of resources for use in delivering its programme of activity, including core funding from annual Participant contributions, supplementary funds (including BID and BIFA and funds received for activities within other projects), and investments by GBIF Participants.

These resources combine as follows:

==== Core Funding

* Supports GBIF Governance structures (Governing Board, committees)
* Supports staffing and operation of GBIF Secretariat to coordinate global activity, including:
** Delivery of global-level IT infrastructure (GBIF.org)
** Coordination of delivery of software components to support Participants and Data Publishers
** Coordination of capacity enhancement activity and information materials for Participants, Data Publishers and Users
** Coordination of supplementary-funded activity and Participant investments in shared GBIF activity
** Monitoring and reporting usage and benefits
** Administrative support for GBIF activities
** Communication, outreach and partnership activities
* Limited funds to support workshops, capacity enhancement and developments to expand or enhance GBIF

==== Supplementary Funding

* Additional funds to support workshops, capacity enhancement and developments to expand or enhance GBIF
* Funding to support Participants and Data Publishers with content mobilization or development of national Biodiversity Information Facilities

==== Participant Investments

* Operating GBIF nodes
* Engaging with and supporting data publishers and users
* Curating data from Data Publishers
* Additional funds or staffing to support workshops, capacity enhancement and developments to expand or enhance GBIF

In past years, Annual Work Programmes have been developed to reflect the use of Core Funding, but this Implementation Plan is intended to offer a framework for GBIF Participants and other stakeholders to take leadership in delivering some of the identified activities and tasks. Where possible, Participants are encouraged to seek funds or allocate staff time to enable progress in areas beyond those for which Core Funding is adequate.

All such commitments reported by GBIF participants have been included within the 2017 Annual Work Programme and will be reported as part of GBIF’s work during the year.

Additional Participant commitments will be most welcome at any stage in the implementation of the 2017 Annual Work Programme and for inclusion in subsequent Annual Work Programmes. Examples of such commitments include (but are not limited to):

* Organization of workshops to develop required new standards or best practice recommendations
* Capacity enhancement and training at regional or global levels, in particular for workshops and projects in regions which are not addressed by current Supplementary Funding sources
* Development of tools or software components to advance GBIF’s work
* Representation of GBIF in international fora
* Recruitment of additional GBIF Participants

Please advise the Secretariat at the earliest possible opportunity of any such proposed commitments. A form is made available for this purpose.

=== Implementation Plan Structure

The Implementation Plan is structured around the five priorities identified in the GBIF Strategic Plan 2017–2021. These are presented here in reverse order from their sequence in the Strategic Plan, and numbered accordingly. This reordering allows the Implementation Plan to place its initial focus squarely on the global network of GBIF Participants and data publishers, building on these foundations to address in turn GBIF’s informatics, content mobilization, curation and delivered products.

For each of the five priorities, the plan presents a series of numbered Activities. These are the major areas where GBIF needs to develop further in the coming period. A rationale and implementation approach is presented for each Activity.

Based on the implementation approach, each Activity includes a series of Tasks. These Tasks are the items that the Annual Work Programmes need to address. They are presented here within each section describing the Activity.
